---
- hosts: all
  tasks:
  - name: Update Selinux
    become: true
    become_method: sudo
    lineinfile:
      regexp: '^SELINUX='
      line: 'SELINUX=enforcing'
      state: present
      dest: /etc/selinux/config
